# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  lint-dockerfile:
    docker:
      - image: docker:stable
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run hadolint
          command: docker images
  test-app:
    docker:
      - image: docker:stable
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Test app
          command: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    docker:
      - image: docker:stable
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: Build and push
          command: "./build_push_image_karsajobs.sh"
workflows:
  lint-test-build-karsajobs:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - lint-dockerfile
