version: "2.1"
orbs:
  docker: circleci/docker@2.5.0
  jobs:
    lint:
      executor: docker/machine
      steps:
        - checkout
        - docker/dockerlint:
            dockerfile: Dockerfile
            treat-warnings-as-errors: true
workflows:
  lint-dockerfile:
    jobs:
      - lint
