version: 2.1
jobs:
  test-app:
    docker:
      - image: cimg/go:1.15.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run test
          command: go test -v -short --count=1 $(go list ./...)

workflows:
  version: 2
  test:
    jobs:
      - test-app
