version: 2.1
orbs:
  docker: circleci/docker@2.5.0
jobs:
  lint-dockerfile:
    docker/hadolint:
      dockerfiles: Dockerfile
      ignore-rules: "DL4005,DL3008"
      trusted-registries: "docker.io,my-company.com:5000"
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: go test -v -short --count=1 $(go list ./...)
workflows:
  lint:
    jobs:
      - docker/hadolint
      - test-app
