version: 2.1
executors:
  my-executor:
    docker:
      - image: hadolint/hadolint:latest
jobs:
  my-job:
    executor: my-executor
    steps:
      - run: echo "Hello executor!"
workflows:
  lint:
    jobs:
      - my-job
