version: 2.1
orbs:
  docker: circleci/docker@2.5.0
  jobs:
    lint:
      executor: docker/machine
      steps:
        - checkout
        - docker/hadolint:
            dockerfiles: Dockerfile
            ignore-rules: "DL4005,DL3008"
            trusted-registries: "docker.io,my-company.com:5000"
workflows:
  lint-test-and-build-karsajobs:
    jobs:
      - lint
