version: 2.1
executors:
  docker:
    docker:
      - image: docker:stable

jobs:
  lint:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hadolint
          command: ls
      - run:
          name: Run Dockerfile
          command: echo "Test command"
      - run:
          name: next test
          command: go test -v -short --count=1 $(go list ./...)

workflows:
  version: 2
  test:
    jobs:
      - lint
