orbs:
  docker: circleci/docker@2.5.0
version: 2.1
workflows:
  lint-test-and-build-karsajobs:
    jobs:
      - lint-dockerfile:
          dockerfiles: Dockerfile
          ignore-rules: "DL4005,DL3008"
          trusted-registries: "docker.io,my-company.com:5000"
